# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69a4d90ea1cceb1bc40ff9033aef18f49a4f5e8863f42ac02bf73280514b4f0f004f12464769c711680faba01e201494557d95afa168ea3cde0fbb80aeeba7aa

test:
  secret_key_base: 89c4bd7ddc8ebd43856d3f76301b0030ec47ef90971d652457054da64e080e6c2eeeafe169b0fd0a102271ef5fe361ce5112136b4de7207020f5f8ccec7aca3a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
